import type { Database } from '@/types/database.types';

/**
 * App-owned public tables (excludes PostGIS catalog tables).
 * Keep this list in sync with generated Database['public']['Tables'] plus
 * the forward migrations that introduce each column.
 */
export const SCHEMA_CONTRACT = {
  admin_audit_log: [
    'id',
    'actor_user_id',
    'action',
    'target_type',
    'target_id',
    'metadata',
    'created_at',
  ],
  ai_bucket_balances: [
    'bucket_kind',
    'bucket_key',
    'period_key',
    'customer_reserved',
    'customer_consumed',
    'platform_reserved',
    'platform_consumed',
    'turns_reserved',
    'turns_consumed',
    'updated_at',
  ],
  ai_budget_config_versions: [
    'id',
    'timezone',
    'paid_account_ceiling_microdollars',
    'free_account_ceiling_microdollars',
    'paid_protected_microdollars',
    'paid_optional_microdollars',
    'guest_session_ceiling_microdollars',
    'guest_session_turn_limit',
    'guest_voice_seconds_limit',
    'guest_day_pool_microdollars',
    'guest_month_pool_microdollars',
    'platform_global_microdollars',
    'maintenance_microdollars',
    'global_paid_core_reserve_microdollars',
    'published_at',
    'created_at',
  ],
  ai_guest_transfers: [
    'guest_id',
    'user_id',
    'period_key',
    'transferred_customer_microdollars',
    'transferred_turns',
    'transferred_at',
  ],
  ai_price_rates: [
    'id',
    'price_version_id',
    'provider',
    'model_id',
    'usage_kind',
    'microdollars_per_million',
    'created_at',
  ],
  ai_price_versions: ['id', 'notes', 'published_at', 'created_at'],
  ai_requests: [
    'id',
    'idempotency_key',
    'status',
    'account_tier',
    'feature_class',
    'user_id',
    'guest_id',
    'provider',
    'model_id',
    'price_version_id',
    'config_version_id',
    'period_key',
    'day_key',
    'as_of',
    'bind',
    'bucket_targets',
    'usage_units',
    'usage_actual',
    'result_payload',
    'quoted_microdollars',
    'reserved_customer_microdollars',
    'reserved_platform_microdollars',
    'settled_customer_microdollars',
    'settled_platform_microdollars',
    'deny_reason',
    'dispatch_acquired_at',
    'customer_released_at',
    'settled_at',
    'created_at',
    'updated_at',
  ],
  badges: ['id', 'name', 'description', 'icon'],
  bite_notes: [
    'id',
    'user_id',
    'redemption_id',
    'restaurant_id',
    'note',
    'rating',
    'created_at',
    'updated_at',
    'is_public',
  ],
  challenge_cycles: [
    'id',
    'user_id',
    'cycle_month',
    'status',
    'swap_count_used',
    'created_at',
  ],
  challenge_items: [
    'id',
    'cycle_id',
    'restaurant_id',
    'slot_number',
    'status',
    'swapped_from_item_id',
  ],
  cron_runs: [
    'id',
    'job_name',
    'started_at',
    'finished_at',
    'status',
    'result',
    'error',
  ],
  markets: ['id', 'name', 'timezone', 'status', 'slug', 'state', 'country', 'currency'],
  partner_sessions: ['token_hash', 'restaurant_id', 'created_at', 'expires_at'],
  redemptions: [
    'id',
    'user_id',
    'restaurant_id',
    'challenge_item_id',
    'token_hash',
    'status',
    'verified_at',
    'created_at',
    'encrypted_code',
    'code_iv',
    'expires_at',
  ],
  restaurant_offers: [
    'id',
    'restaurant_id',
    'discount_amount_cents',
    'min_spend_cents',
    'max_redemptions_per_month',
    'active',
    'created_at',
  ],
  restaurant_orgs: ['id', 'name', 'market_id'],
  restaurants: [
    'id',
    'org_id',
    'market_id',
    'name',
    'cuisine_tags',
    'address',
    'lat',
    'lon',
    'location',
    'status',
    'created_at',
    'description',
    'price_range',
    'neighborhood',
    'image_url',
    'verification_code',
    'google_place_id',
    'google_photo_url',
    'slug',
    'is_dairy_free',
    'is_vegan',
    'is_halal',
    'pin_hash',
    'updated_at',
  ],
  stripe_events: [
    'event_id',
    'event_type',
    'object_id',
    'livemode',
    'api_version',
    'stripe_created',
    'payload',
    'status',
    'attempts',
    'last_error',
    'received_at',
    'claimed_at',
    'claim_token',
    'processed_at',
    'available_at',
  ],
  user_badges: ['user_id', 'badge_id', 'awarded_at'],
  user_preferences: ['user_id', 'excluded_cuisines'],
  user_profiles: [
    'id',
    'email',
    'role',
    'dietary_flags',
    'allergy_flags',
    'distance_band',
    'stripe_customer_id',
    'stripe_subscription_id',
    'subscription_status',
    'current_period_end',
    'full_name',
    'username',
    'phone_number',
    'address',
    'distance_preference',
    'wants_cocktail_experience',
    'is_admin',
    'address_street',
    'address_city',
    'address_state',
    'address_zip',
  ],
  webhook_outbox: [
    'effect_key',
    'effect_type',
    'source_event_id',
    'status',
    'attempts',
    'last_error',
    'claimed_at',
    'claim_token',
    'available_at',
    'sent_at',
    'created_at',
    'payload',
  ],
} as const;

export const POSTGIS_TYPE_TABLES = [
  'spatial_ref_sys',
  'geography_columns',
  'geometry_columns',
] as const;

export type AppTableName = keyof typeof SCHEMA_CONTRACT;

export type DatabaseTableName = keyof Database['public']['Tables'];

/** Compile-time: every contracted table exists on generated Database types. */
export type SchemaContractTablesExist = {
  [K in AppTableName]: Database['public']['Tables'][K]['Row'];
};
